[package]
name = "rust-chat"
version = "0.1.0"
edition = "2024"

[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
serde = "1.0.228"
serde_json = "1.0.148"
